-- Formatage de l'affichage
COLUMN NomEtu FORMAT A15
COLUMN NomIUT FORMAT A15
COLUMN Dept FORMAT A15
COLUMN Decision FORMAT A15

COLUMN NomIut NEW_VALUE MGRVAR
TTITLE CENTER "BILAN CANDIDATURES : " MGRVAR SKIP 2

SET FEEDBACK OFF
SET NEWPAGE 1
SET LINESIZE 100
SET PAGESIZE 100
BREAK ON NomIut SKIP PAGE ON NomEtu ROW SKIP 1


-- Requête
SELECT NomIUT, NomEtu, Moy, Dept, Decision
FROM ETUDIANT INNER JOIN CANDIDATER ON (ETUDIANT.NumEtu = CANDIDATER.NumEtu)
ORDER BY NomIut ASC, NomEtu ASC;

-- Réinitialisation du formatage de l'affichage
CLEAR COLUMNS
CLEAR BREAKS

SET UNDERLINE '-'
SET colsep ' '

TTITLE OFF
BTITLE OFF