-- Formatage de l'affichage
COLUMN NomEtu FORMAT A15
COLUMN NomIUT FORMAT A15
COLUMN Dept FORMAT A15
COLUMN Decision FORMAT A15

TTITLE "BILAN CANDIDATURES : IUT Dijon"

SET FEEDBACK ON
SET NEWPAGE 1
SET LINESIZE 5000
SET PAGESIZE 5000
BREAK ON NomIut ON NomEtu


-- Requête
SELECT NomIUT, NomEtu, Dept, Decision
FROM ETUDIANT INNER JOIN CANDIDATER ON (ETUDIANT.NumEtu = CANDIDATER.NumEtu)
ORDER BY NomIut ASC, NomEtu ASC;

-- Réinitialisation du formatage de l'affichage
CLEAR COLUMNS
CLEAR BREAKS

SET UNDERLINE '-'
SET colsep ' '

TTITLE OFF
BTITLE OFF 