-- Formatage de l'affichage
clear screen

COLUMN NomEtu FORMAT A15
COLUMN NomIUT FORMAT A15
COLUMN Dept FORMAT A15
COLUMN Decision FORMAT A15
COLUMN Moy FORMAT 999

COLUMN NomIut NEW_VALUE l_NomIut
TTITLE CENTER "BILAN CANDIDATURES : " l_NomIut SKIP 2 -
CENTER '===============================' SKIP 2
BTITLE RIGHT FORMAT 99 'Page' SQL.PNO

SET FEEDBACK OFF
SET NEWPAGE 1
SET LINESIZE 100
SET PAGESIZE 100
BREAK ON NomIut SKIP PAGE ON NomEtu ROW SKIP 1
COMPUTE AVG LABEL 'avg' OF Moy ON NomIut;

-- Requête
SPOOL exo2_3.txt

SELECT NomIUT, NomEtu, Moy, Dept, Decision
FROM ETUDIANT INNER JOIN CANDIDATER ON (ETUDIANT.NumEtu = CANDIDATER.NumEtu)
ORDER BY NomIut ASC, NomEtu ASC;

SPOOL OFF

-- Réinitialisation du formatage de l'affichage
CLEAR COLUMNS
CLEAR BREAKS

SET UNDERLINE '-'
SET colsep ' '

TTITLE OFF
BTITLE OFF